# Generated by Django 3.0.7 on 2020-06-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nombre')),
                ('internal_id', models.CharField(max_length=4, unique=True, verbose_name='Codigo interno')),
                ('cuit', models.CharField(max_length=11, unique=True, verbose_name='CUIT')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('name',),
            },
        ),
    ]
