# Generated by Django 3.0.7 on 2020-06-20 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extras.Clients', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extras.InvoicesTypes', verbose_name='Tipo Comprobante'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
    ]
